### PR TITLE
Prac 07 feedback

### PR DESCRIPTION
**Pull request by KuiMengcen**

### CODE REVIEW

**Comment by KuiMengcen** [comment]
@ LiXinyue321
@jiaxuanliu908
@lowyiheng

**Comment by lowyiheng** [comment]
good program

**Comment by KuiMengcen** [comment]
@LiXinyue321

**Comment by LiXinyue321** [comment]
good code and working hard.

**Comment by jiaxuanliu908** [comment]
great！！！！！

**Pull request merged**
